Checking whether this pull request makes sense
PyGLImER/PyGLImER pull request #136
Opened 2023-02-06 15:17 UTC by lsawade

Hi Peter,

I think I didn't pull something from your branch at some point, and now it's fast-forwarding and rewinding and stuff. There were 0 merge conflicts, but before merging this I/we should go through at least some of the changes, just to see whether they make sense. 

- [x] Tests are passing
- [x] No merge-conflicts
- [ ] Am I breaking something?

2023-02-08 12:28 UTC, PeterMakus commented
Hi Lucas,
it seems like you didn't add any changes to this merge request? It's just the two PRs from ´´dev´´ into your branch? Can you double-check?

2023-02-13 14:39 UTC, lsawade commented
Did I mess something up...

2023-02-13 14:40 UTC, lsawade commented
> Hi Lucas,
> it seems like you didn't add any changes to this merge request? It's just the two PRs from ´´dev´´ into your branch? Can you double-check?

I you look at the diff, I made a bunch of changes that are hiding in merges...

2023-02-13 15:14 UTC, PeterMakus requested changes
seems ok to me. Please change the one point that I commented. Also, I am not sure wrt the impact of ``download_chunk_size_in_mb``

2023-02-13 15:14 UTC, PeterMakus commented on src/pyglimer/waveform/download.py
> +        fh.setLevel(logging.info)
this is not correct. ``logging.info`` is a function, whereas ``logging.INFO`` is the actual logging level.

2023-02-14 08:56 UTC, PeterMakus commented
looks good. Seems like there is an error with lint (So probably some cosmetic thing). We should probably have a separate action for linting and not run it together with unittest, sorry for that.
After the linting is fixed, we can merge

2023-02-27 07:47 UTC, PeterMakus commented
@lsawade Can you check to fix the things that make the unittests fail? If I remember correctly it was only a *listing issue*. But otherwise I think this is almost mergeable.

2023-02-28 18:34 UTC, lsawade commented
I have made some more mini-updates that I'm going to push and as part of that I'm going to fix the formatting errors.

2023-07-07 06:46 UTC, PeterMakus commented
again some linting problems, but after you fixed this, we can merge.

2023-07-08 05:00 UTC, merged